/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package usecaseassistant;

import java.util.ArrayList;
import javax.swing.JFrame;

/**
 *
 * @author Deryk Mathew
 */
public class UseCaseAssistant extends javax.swing.JPanel {

    /**
     * Creates new form MainFormPanel
     * @param name
     */
    public UseCaseAssistant(String name) {
        initComponents();
        systemName = name;
        sysName.setText(systemName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editUCButton = new javax.swing.JButton();
        newUCButton = new javax.swing.JButton();
        deleteUCButton = new javax.swing.JButton();
        ucLabelList = new javax.swing.JLabel();
        sysNameLabel = new javax.swing.JLabel();
        sysName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        UCList = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();

        editUCButton.setText("Edit UC");
        editUCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUCButtonActionPerformed(evt);
            }
        });

        newUCButton.setText("New UC");
        newUCButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                newUCButtonMousePressed(evt);
            }
        });

        deleteUCButton.setText("Delete UC");

        ucLabelList.setText("Use Cases:");

        sysNameLabel.setText("System Name:");

        jScrollPane1.setViewportView(UCList);

        jButton1.setText("Save System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sysNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sysName))
                    .addComponent(ucLabelList)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(deleteUCButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(editUCButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(newUCButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sysNameLabel)
                    .addComponent(sysName))
                .addGap(36, 36, 36)
                .addComponent(ucLabelList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(newUCButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editUCButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteUCButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editUCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUCButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editUCButtonActionPerformed

    private void newUCButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newUCButtonMousePressed
        createAndShowGUI();
    }//GEN-LAST:event_newUCButtonMousePressed

    private void createAndShowGUI() {
        //Create and set up the window.
        ucID++;
        JFrame frame = new JFrame("Add New Use Case");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        UseCaseCreation ucc = new UseCaseCreation(ucID);
        ucl.add(ucc);
        frame.getContentPane().add(ucc);

        //Display the window.
        frame.pack();
        frame.setVisible(true);
    }

    private int ucID;
    private String systemName;
    private ArrayList<UseCaseCreation> ucl = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList UCList;
    private javax.swing.JButton deleteUCButton;
    private javax.swing.JButton editUCButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newUCButton;
    private javax.swing.JLabel sysName;
    private javax.swing.JLabel sysNameLabel;
    private javax.swing.JLabel ucLabelList;
    // End of variables declaration//GEN-END:variables
}
